version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:3.12

    volumes:
      - ../..:/workspaces:cached

    environment:
      PYTHONUNBUFFERED: 1

    command: sleep infinity
    
    networks:
      - dev-net

  postgres:
    image: postgres:latest

    restart: always

    container_name: postgres

    ports:
      - "5432:5432"
    
    expose:
      - "5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: teaine
      POSTGRES_DB: teaine
      POSTGRES_PASSWORD: teaine
    
    networks:
      - dev-net

  qdrant:
    image: qdrant/qdrant:latest

    restart: always

    container_name: qdrant

    ports:
      - "6333:6333"
      - "6334:6334"
    
    expose:
      - "6333"
      - "6334"
      - "6335"
    
    volumes:
      - qdrant-data:/qdrant/storage

    environment:
      QDRANT__LOG_LEVEL: INFO
      QDRANT__SERVICE__API_KEY: teaine
      QDRANT__SERVICE__ENABLE_TLS: false
    
    networks:
      - dev-net

volumes:
  postgres-data:
  qdrant-data:

networks:
  dev-net: